baseURL = 'https://achanandhi.netlify.app/'
languageCode = 'en-us'
title = 'Achanandhi M'
theme = "hugo-PaperMod"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"
weight = 20

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects"
weight = 30

[[menu.main]]
identifier = "experience"
name = "Experience"
url = "/experience"
weight = 40

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search"
weight = 60

[[menu.main]]
identifier = "tags"
name="Tags"
url="/tags"
weight=50

[params]
showToc = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
hideMeta = false
author= ["Achanandhi M"]
env = "production"
hideDescriptionInList = false

  [params.profileMode]
  enabled = true
  title = "Achanandhi M"
  subtitle = "As a Web Application Intern at [**Itransz.in**](https://itransz.in/), I've been focusing more on building web applications. My enthusiasm lies in working with Kubernetes ,Docker, and other projects managed by CNCF. I love the philosophy of FOSS, and I am a proud Linux (fedora) user. I am a Self-taught programmer, AWS fascinates me a lot. It all started with the cloud. That curiosity made me like computer science , especially technology. I used to share my thoughts on tech quite often. **_My life's greatest success lies in making technology and IT accessible to rural students and helping them become a part of the IT world_**"
 
  imageUrl = "home/home.jpeg"
  imageWidth = 220
  imageHeight = 220

 [[params.profileMode.buttons]]
  name = "Resume"
  url = "https://drive.google.com/file/d/1GL-kUy5oC2EtFSMDqxGmFKrOHGpyzZ2g/view?usp=sharing"

  [params.cover]
  hiddenInList = false
  hiddenInSingle = false

  [[params.socialIcons]]
  name = "email"
  url = "mailto:achanandhi.m@gmail.com"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/achanandhi-m/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Achanandhi-M"

  [[params.socialIcons]]
  name="X"
  url="https://twitter.com/AchanandhiM"

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[markup.goldmark.renderer]
unsafe = true
